In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Matrix A\n",b,"\n\nMatrix B\n",b)

Matrix A
 [[9 8 7]
 [6 5 4]
 [3 2 1]] 

Matrix B
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [2]:
add=np.add(a,b)
print("Added Matrix \n",add)

Added Matrix 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [3]:
sub=np.subtract(a,b)
print("Subtracted Matrix \n",sub)

Subtracted Matrix 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [4]:
mul=np.dot(a,b)
print("Product Matrix \n",mul)

Product Matrix 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
trans=np.transpose(b)
print("Transpose\n",trans)

Transpose
 [[9 6 3]
 [8 5 2]
 [7 4 1]]


In [10]:
list=[8,4,6,2,5,3,8,2,5]
n=np.array(list).reshape(3,3)
n

array([[8, 4, 6],
       [2, 5, 3],
       [8, 2, 5]])

In [18]:
def matrix():
    elements=[]
    column=int(input("Enter the number of column"))
    row=int(input("Enter the number of rows"))
    element=column*row
    print("enter the elements of matrix")
    for i in range(0,element):
        e=int(input())
        elements.append(e)
    n=np.array(elements).reshape(row,column)
    return n
A=matrix()
B=matrix()
print("Matrix A\n",A,"\nMatrix B\n",B)

Enter the number of column2
Enter the number of rows3
enter the elements of matrix
1
2
3
4
5
6
Enter the number of column3
Enter the number of rows2
enter the elements of matrix
9
8
7
65
5
4
Matrix A
 [[1 2]
 [3 4]
 [5 6]] 
Matrix B
 [[ 9  8  7]
 [65  5  4]]
